### ISSUE TITLE
How can I fix it

### ISSUE THREAD

**Issue by Bilibili-Summer** [SwaggyMacro/cs2-WeaponPaints-Website#10]
如何修复此错误(进入网站点击Steam登录):
```
InternalOpenIDError: Failed to discover OP endpoint URL
    at C:\Users\Administrator\Desktop\cs2-WeaponPaints-Website-0.2.2\node_modules\@passport-next\passport-openid\lib\passport-openid\strategy.js:249:52
    at C:\Users\Administrator\Desktop\cs2-WeaponPaints-Website-0.2.2\node_modules\openid\openid.js:757:14
    at C:\Users\Administrator\Desktop\cs2-WeaponPaints-Website-0.2.2\node_modules\openid\openid.js:547:13
    at C:\Users\Administrator\Desktop\cs2-WeaponPaints-Website-0.2.2\node_modules\openid\openid.js:503:11
    at C:\Users\Administrator\Desktop\cs2-WeaponPaints-Website-0.2.2\node_modules\openid\http.js:41:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
感谢

**Comment by Bilibili-Summer** [comment]
服务器可以正常访问steamcommunity

**Comment by Bilibili-Summer** [comment]
使用国外服务器解决了
