### ISSUE TITLE
在登录Steam时遇到这个报错

### ISSUE THREAD

**Issue by Max66888** [SwaggyMacro/cs2-WeaponPaints-Website#16]
如下，我在登录Steam时遇到这个报错，并且始终登录不上无法使用
在这个地址http://[ip]/api/auth/steam
InternalOpenIDError: Failed to discover OP endpoint URL
    at /opt/cs2_plugins/cs2-WeaponPaints-Website-main/node_modules/@passport-next/passport-openid/lib/passport-openid/strategy.js:249:52
    at /opt/cs2_plugins/cs2-WeaponPaints-Website-main/node_modules/openid/openid.js:757:14
    at /opt/cs2_plugins/cs2-WeaponPaints-Website-main/node_modules/openid/openid.js:547:13
    at /opt/cs2_plugins/cs2-WeaponPaints-Website-main/node_modules/openid/openid.js:503:11
    at /opt/cs2_plugins/cs2-WeaponPaints-Website-main/node_modules/openid/http.js:41:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by mete0rxsc** [comment]
同问  请问解决了吗

**Comment by Max66888** [comment]
> 同问 请问解决了吗

这个问题解决了，我全部重新装了一遍，不会报这个错误了，但是登录成功跳转回去还是显示未登录，你成功了吗
还有你是不是一个小时前在资料库帖子下留言这个的哈哈哈哈
`[Mete0r]() 一级用户组[@Ta]() 1小时前 [ 0](javascript:;)
 16楼
大佬  报错
InternalOpenIDError:  Failed  to  discover  OP  endpoint  URL
        at  F:\WeaponPaints-Website\website\node_modules\@passport-next\passport-openid\lib\passport-openid\strategy.js:249:52
        at  F:\WeaponPaints-Website\website\node_modules\openid\openid.js:757:14
        at  F:\WeaponPaints-Website\website\node_modules\openid\openid.js:547:13
        at  F:\WeaponPaints-Website\website\node_modules\openid\openid.js:503:11
        at  F:\WeaponPaints-Website\website\node_modules\openid\http.js:41:9
        at  processTicksAndRejections  (node:internal/process/task_queues:96:5)
怎么解决啊`
