### ISSUE TITLE
无法启动 message: 'Claimed identity is invalid.'

### ISSUE THREAD

**Issue by HoshinoDesu** [SwaggyMacro/cs2-WeaponPaints-Website#4]
请问这是什么问题导致的？抱歉我看不懂报错...
```
root@armbian:~/skin# npm run startLinux

> WeaponPaints@0.2.2 startLinux
> nodemon -x 'node . || touch src/app.js'

[nodemon] 3.1.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node . || touch src/app.js`
/root/skin/node_modules/passport-steam/lib/passport-steam/strategy.js:108
    if (!req.query['openid.claimed_id']?.startsWith(OPENID_CHECK.claimed_id)) return done(null, false, { message: 'Claimed identity is invalid.' });
                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/skin/node_modules/passport-steam/lib/passport-steam/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[nodemon] clean exit - waiting for changes before restart
[nodemon] restarting due to changes...
[nodemon] starting `node . || touch src/app.js`
/root/skin/node_modules/passport-steam/lib/passport-steam/strategy.js:108
    if (!req.query['openid.claimed_id']?.startsWith(OPENID_CHECK.claimed_id)) return done(null, false, { message: 'Claimed identity is invalid.' });
                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/skin/node_modules/passport-steam/lib/passport-steam/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[nodemon] clean exit - waiting for changes before restart
[nodemon] Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch '/root/skin/src/public/images/econ/stickers/katowice2019/sig_bntet_png.png'
```

**Comment by HoshinoDesu** [comment]
是我铸币了，忘了看版本...

**Comment by HoshinoDesu** [comment]
呃...好吧，出现新问题了...
无法连接数据库
在网站中点击换肤 网站程序就会崩溃
下面是纪录
```
root@armbian:~/skin# npm run startLinux

> WeaponPaints@0.2.2 startLinux
> nodemon -x 'node . || touch src/app.js'

[nodemon] 3.1.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node . || touch src/app.js`
App is running on http://localhost:80
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
Socket connected
[nodemon] Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch '/root/skin/src/public/images/econ/stickers/katowice2019/sig_edward_foil_png.png'
root@armbian:~/skin# Socket connected
/root/skin/src/app.js:304
        if (results.length >= 1) {
                    ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Query.<anonymous> (/root/skin/src/app.js:304:21)
    at Query.<anonymous> (/root/skin/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/root/skin/node_modules/mysql/lib/Connection.js:488:16)
    at Sequence.end (/root/skin/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /root/skin/node_modules/mysql/lib/protocol/Protocol.js:236:14
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v20.12.0
```

**Comment by HoshinoDesu** [comment]
已经成功解决~
