### ISSUE TITLE
InternalOpenIDError: Failed to discover OP endpoint URL

### ISSUE THREAD

**Issue by wudi-7mi** [SwaggyMacro/cs2-WeaponPaints-Website#6]
点击登录遇到问题：

```
InternalOpenIDError: Failed to discover OP endpoint URL
    at /data/user23202791/lgsm/wp_manage/node_modules/@passport-next/passport-openid/lib/passport-openid/strategy.js:249:52
    at /data/user23202791/lgsm/wp_manage/node_modules/openid/openid.js:757:14
    at /data/user23202791/lgsm/wp_manage/node_modules/openid/openid.js:547:13
    at /data/user23202791/lgsm/wp_manage/node_modules/openid/openid.js:503:11
    at /data/user23202791/lgsm/wp_manage/node_modules/openid/http.js:41:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

一开始认为是网络连接问题，配置了 steamcommunity 302 之后测试连接社区页面正常：

```shell
(base) user23202791@Ubuntu-6-3090:~/lgsm/wp_manage$ curl https://steamcommunity.com/openid
<?xml version="1.0" encoding="UTF-8"?>
<xrds:XRDS xmlns:xrds="xri://$xrds" xmlns="xri://$xrd*($v*2.0)">
        <XRD>
                <Service priority="0">
                        <Type>http://specs.openid.net/auth/2.0/server</Type>
                        <URI>https://steamcommunity.com/openid/login</URI>
                </Service>
        </XRD>
</xrds:XRDS>

(base) user23202791@Ubuntu-6-3090:~/lgsm/wp_manage$ curl https://steamcommunity.com
<!DOCTYPE html>
<html class=" responsive" lang="en">
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
                        <meta name="viewport" content="width=device-width,initial-scale=1">
                <meta name="theme-color" content="#171a21">
                <title>Steam Community</title>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
......(后面网页内容省略)
```

但是点击登录后上述问题依然存在，请问是否可能是其他问题？

**Comment by wudi-7mi** [comment]
再提供一张主页常报的错误作为参考：
![image](https://github.com/SwaggyMacro/cs2-WeaponPaints-Website/assets/122330888/a1eed74b-9831-472e-914b-6850df24c75f)

**Comment by SwaggyMacro** [comment]
重复issue #2 passport在获取Steam的API接口 但网络原因无法获取

**Comment by wudi-7mi** [comment]
> 重复issue #2 passport在获取Steam的API接口 但网络原因无法获取

但是curl可以获取到社区页面，服务器可以连接到社区接口，是passport库走的连接路线不一样吗？

**Comment by wudi-7mi** [comment]
> > 重复issue #2 passport在获取Steam的API接口 但网络原因无法获取
> 
> 但是curl可以获取到社区页面，服务器可以连接到社区接口，是passport库走的连接路线不一样吗？

似乎在刷新DNS，重启服务器后问题解除。
